version: "3"

services:
    api:
        container_name: api
        build: ./api-fake
        volumes: 
            - ./api-fake:/app
        ports:
            - "5000:5000"

    database:
        container_name: postgres
        image: postgres
        restart: always
        environment: 
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: teste
        volumes: 
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports: 
            - "5432:5432"
